services:
  - type: web
    name: mini-blog
    env: php
    buildCommand: './build.sh'
    startCommand: 'php artisan serve --host 0.0.0.0 --port 10000'
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
