services:
  - type: web
    name: laravel-mini-blog
    env: docker
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: sql.freedb.tech
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: freedb_mini_blog
      - key: DB_USERNAME
        value: freedb_bothien09
      - key: DB_PASSWORD
        value: FB7?n5vyFss&C2u
    dockerfilePath: Dockerfile
    autoDeploy: true
    buildFilter:
      paths:
        - "**/*"
